# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d433b701b74705b4d13aa2f94b5ab3c7442e2e0483347f07cdcb2d4d82ba83ddea3936b98652d7e453105487b97ca6c223c262a4f9df6d41a310b8276468b15

test:
  secret_key_base: 284f700738b82dfbbb87980a57e8f18d5b483992d6ac3f032c726ba0eb327d824a218c8fc62e92eddb6b606d748e6b70ccd647e275d84f824de155b160caa936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
